### ISSUE TITLE
Remove dependency on ifconfig 

### ISSUE THREAD

**Issue by iommu** [sakshi2912/Proximity#12]
ifconfig has been depreciated

**Comment by Gituser143** [comment]
@sakshi2912 @nsankethreddy can I take up this issue?

**Comment by sakshi2912** [comment]
> @sakshi2912 @nsankethreddy can I take up this issue?

Sure.

**Comment by Gituser143** [comment]
@sakshi2912 just to confirm, the dependency is only in server.py right? I couldn't find one on client.

**Comment by nsankethreddy** [comment]
@Gituser143 refer to the open PR from @iommu, he was trying to work on the same issue. You could use this try out a different approach from what was done already.

**Comment by nsankethreddy** [comment]
> @sakshi2912 just to confirm, the dependency is only in server.py right? I couldn't find one on client.

Yes, the dependency is only in server.py

**Comment by Gituser143** [comment]
Why didn't `socket.gethostbyname()` work on a linux system though?

**Comment by nsankethreddy** [comment]
Yeah, it should work. But I have no clue why it isn't working.

**Comment by nsankethreddy** [comment]
> Why didn't `socket.gethostbyname()` work on a linux system though?
> As long as the python dependency is satisfied. It should work.

Actually, it does work, but it doesn't give the LAN relative IP, which is what is required for this application to work.
