### ISSUE TITLE
Add a function to send "Images" 

### ISSUE THREAD

**Issue by sakshi2912** [sakshi2912/Proximity#14]
The current implementation supports sending only text messages.
Add a functionality to be able to send Images across the socket.

**Comment by RAMYA-CP** [comment]
Hey I would like to take this up

**Comment by sakshi2912** [comment]
> Hey I would like to take this up

Sure.
When the user has to send an image, he'll have to type **image: path-to-image** 

At the receiver end, store all the received images into a folder called "Proximity_images".

**Comment by RAMYA-CP** [comment]
Hey I have created a pull request for the same please do let me know if that's what was expected!!!
