### ISSUE TITLE
Add a function to send files

### ISSUE THREAD

**Issue by sakshi2912** [sakshi2912/Proximity#15]
Add a functionality to send files of some supported formats like pdf,txt,docx across the socket.

**Comment by anirudhRowjee** [comment]
Hi, can I work on this?

**Comment by sakshi2912** [comment]
> Hi, can I work on this?

Sure , I've assigned you to the issue.

**Comment by sakshi2912** [comment]
hey, @anirudhRowjee 
Let the use type " **file: path-to-file** " , in order to send the particular file.

**Comment by RakshithRAcharya** [comment]
Hey, can I work on this?

**Comment by anirudhRowjee** [comment]
I'd like to take some time to understand the codebase better, so I'm unassigning myself. If anyone else wants to take this up in the meanwhile, please feel free

**Comment by sakshi2912** [comment]
> Hey, can I work on this?

yes, go aheaad.

**Comment by sakshi2912** [comment]
> I'd like to take some time to understand the codebase better, so I'm unassigning myself. If anyone else wants to take this up in the meanwhile, please feel free

Sure! No worries

**Comment by RakshithRAcharya** [comment]
Can we use ftplib library for this??

**Comment by sakshi2912** [comment]
> Can we use ftplib library for this??

You can use any library. But try to use a library which is compatible with both Linux and Windows.
