### ISSUE TITLE
Add a progress bar to show the file being sent.

### ISSUE THREAD

**Issue by sakshi2912** [sakshi2912/Proximity#18]
When the user types file:path_to_file , the immediate message is File sent.
Add a progress bar which would indicate how much of the file has been sent and how much is still left.
This progress bar should be shown at both server and client sides.

**Comment by raghuchandan1** [comment]
Can you assign this issue to me

**Comment by sakshi2912** [comment]
> Can you assign this issue to me

Sure, go ahead!
