### ISSUE TITLE
Improve how the status messages are being displayed

### ISSUE THREAD

**Issue by nsankethreddy** [sakshi2912/Proximity#19]
Move the status messages [eg:("Image sent", "Image received", "An error occurred")] to the middle of the screen.

**Comment by Sameer-Mann** [comment]
@nsankethreddy i would like to work on could u tell me a little bit how the messages are displayed?

**Comment by nsankethreddy** [comment]
Hey @Sameer-Mann if you could run the server and client program and send images/files between the nodes. You will notice that the " image sent "," image received successfully " and all such similar messages  are just getting printed on the left side of the shell, so all I need you to do is move all the status messages to the centre of the shell.

**Comment by Sameer-Mann** [comment]
ok got it
