### ISSUE TITLE
Add support for Mac OS

### ISSUE THREAD

**Issue by nsankethreddy** [sakshi2912/Proximity#8]
The current implementation works on Windows and Linux, need to add support for Mac OS

**Comment by wevnasc** [comment]
Could you assign that for me, but before I to start what exactly doesn't work for Mac OS?

**Comment by energiesparlampe** [comment]
Hi there,
I have addressed this issue in my pull request #10, where I implemented support for macOS systems. Can you by chance assign me for this issue?

**Comment by nsankethreddy** [comment]
> @nsankethreddy could you assign that for me? , but before I to start what exactly doesn't work for Mac OS?

Hey, issue was already addressed by @energiesparlampe thank you for your interest

**Comment by nsankethreddy** [comment]
Thank you @energiesparlampe
